### ISSUE TITLE
Assignments?

### ISSUE THREAD

**Issue by AB1908** [AsliRoy/Compiler-Design-Laboratory#1]
What were the assignments? The solutions are definitely appreciated though.  😅 

(Same for OS Lab)

**Comment by AsliRoy** [comment]
There are some labs with the dates mentioned. I don't think I have all of them. I may have a pdf of the entire lab though, somewhere. You'll get the questions, the code and the output screenshots in one place. Will look it up and let you know.

**Comment by AsliRoy** [comment]
@AB1908 , got them , although they were pretty fragmented. You can find it here  [https://github.com/AsliRoy/Compiler-Design-Laboratory/tree/master/Assignments(pdf)](url). Will be pretty useful for anybody who gets Sumanta Pyne. 
As for OS Lab, the questions have been repeated for 2 years in a row. So the topics are mentioned, you can blindly assume that the same problems will be there. Again helps, anyone in BKP's lab. 

Do let others know and spread the love. 
Best,
AsliRoy

**Comment by AB1908** [comment]
Thanks! Much appreciated 😃
